"""Adiciona a tabela solicitacoes

Revision ID: 5e50931e55f3
Revises: d3820cac5cc6
Create Date: 2025-07-24 10:19:29.447092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e50931e55f3'
down_revision: Union[str, Sequence[str], None] = 'd3820cac5cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revenda_id', sa.String(length=50), nullable=False),
    sa.Column('setor_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('data_inicio_proc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_fim_proc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_mensagem', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_id'), 'solicitacoes', ['id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_revenda_id'), 'solicitacoes', ['revenda_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_setor_id'), 'solicitacoes', ['setor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacoes_setor_id'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_revenda_id'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_id'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    # ### end Alembic commands ###
