"""Adiciona revenda_id a tabela solicitacoes

Revision ID: a8a81e726ada
Revises: 5e50931e55f3
Create Date: 2025-07-24 10:41:27.264518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a81e726ada'
down_revision: Union[str, Sequence[str], None] = '5e50931e55f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
